spring:
  application:
    name: AITrip
  jpa:
    properties:
      hibernate:
        format_sql: 'TRUE'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  amadeus:
    api:
      key: ${AMADEUS_API_KEY}
      secret: ${AMADEUS_API_SECRET}
  openai:
    api:
      key: ${OPENAI_API_KEY}