spring:
  main:
    lazy-initialization: true
  application:
    name: AITrip
  jpa:
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  amadeus:
    api:
      test:
        key: ${AMADEUS_API_TEST_KEY}
        secret: ${AMADEUS_API_TEST_SECRET}
        url: https://test.api.amadeus.com/
      production:
        key: ${AMADEUS_API_PRODUCTION_KEY}
        secret: ${AMADEUS_API_PRODUCTION_SECRET}
        url: https://api.amadeus.com/
  openai:
    api:
      key: ${OPENAI_API_KEY}
  numverify:
    api:
      key: ${NUMVERIFY_API_KEY}
server:
  port: ${PORT:8080}
